[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
skip = ["signxml/__init__.py", "signxml/xades/__init__.py"]
skip_gitignore = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
per-file-ignores = {"signxml/__init__.py" = ["F401"], "signxml/xades/__init__.py" = ["F401"], "signxml/verifier.py" = ["E721"]}
